efr.hostname=https://CLIENT_ID.enterpriseflowsrepository.com

# EFR OIDC configuration structure
efr.oidc.hostname=${efr.hostname}/auth
efr.oidc.realm=efr
efr.oidc.grant-type=password
efr.oidc.client-id=REPLACE_ME
efr.oidc.client-secret=REPLACE_ME
efr.oidc.username=REPLACE_ME
efr.oidc.password=REPLACE_ME

# EFR trace meta-data
route.datacenter=test-cluster
route.name=test-route
route.version=1.0.0
route.id=${quarkus.application.name}
environment=test

# Misc
efr.traces.max-headers-size=4095
efr.traces.max-stacktrace-size=4095